const TemplateLibrary = {
    gallery: [
        { id: 'white-cube', name: 'White Cube Gallery', description: 'Classic minimalist gallery', category: 'gallery', baseResolution: { width: 4000, height: 3000 }, scene: { background: '#f8f8f8', floor: { color: '#e8e8e8', reflection: 0.15 }, lighting: { ambient: 0.4, key: { x: 0.6, y: 0.3, intensity: 0.8, warmth: 4000 } }, placeholder: { x: 0.5, y: 0.48, width: 0.35, height: 0.45 } } },
        { id: 'concrete-brutalist', name: 'Concrete Brutalist', description: 'Raw concrete walls with dramatic lighting', category: 'gallery', baseResolution: { width: 4000, height: 3000 }, scene: { background: '#3a3a3a', floor: { color: '#2a2a2a', reflection: 0.1 }, lighting: { ambient: 0.2, key: { x: 0.3, y: 0.2, intensity: 1.2, warmth: 3000 } }, placeholder: { x: 0.5, y: 0.5, width: 0.4, height: 0.5 } } },
        { id: 'dark-spotlight', name: 'Dark Spotlight Gallery', description: 'Dramatic museum spotlight', category: 'gallery', baseResolution: { width: 3800, height: 2800 }, scene: { background: '#1a1a1a', floor: { color: '#0a0a0a', reflection: 0.2 }, lighting: { ambient: 0.15, key: { x: 0.5, y: 0.15, intensity: 1.5, warmth: 3200 } }, placeholder: { x: 0.5, y: 0.45, width: 0.32, height: 0.55 } } },
        { id: 'floating-spotlight', name: 'Floating Spotlight', description: 'Artwork in dramatic light beam', category: 'gallery', baseResolution: { width: 3600, height: 2400 }, scene: { background: '#050505', lighting: { ambient: 0.05, key: { x: 0.5, y: 0, intensity: 2.0, warmth: 3000, cone: 0.3 } }, placeholder: { x: 0.5, y: 0.5, width: 0.3, height: 0.4, floating: true } } }
    ],
    residential: [
        { id: 'modern-minimal', name: 'Modern Minimal', description: 'Clean contemporary living space', category: 'residential', baseResolution: { width: 4200, height: 2800 }, scene: { background: '#f5f5f0', floor: { color: '#d4c4b0', type: 'wood', reflection: 0.05 }, lighting: { ambient: 0.5, natural: { x: 0.8, y: 0.3, intensity: 0.7, warmth: 5500 } }, placeholder: { x: 0.4, y: 0.42, width: 0.25, height: 0.35 } } },
        { id: 'scandinavian', name: 'Scandinavian Home', description: 'Warm Nordic interior', category: 'residential', baseResolution: { width: 4000, height: 2700 }, scene: { background: '#f0ebe4', floor: { color: '#e6dcc8', type: 'light-wood' }, lighting: { ambient: 0.55, natural: { x: 0.2, y: 0.35, intensity: 0.9, warmth: 5000 } }, placeholder: { x: 0.5, y: 0.45, width: 0.3, height: 0.35 } } },
        { id: 'luxury-penthouse', name: 'Luxury Penthouse', description: 'High-end penthouse with city view', category: 'residential', baseResolution: { width: 4500, height: 3000 }, scene: { background: '#2a2a2a', floor: { color: '#1a1a1a', type: 'dark-wood', reflection: 0.15 }, lighting: { ambient: 0.3, natural: { x: 0.9, y: 0.2, intensity: 0.6, warmth: 6000 } }, placeholder: { x: 0.35, y: 0.4, width: 0.28, height: 0.4 } } },
        { id: 'hamptons-coastal', name: 'Hamptons Coastal', description: 'Bright coastal interior', category: 'residential', baseResolution: { width: 4000, height: 2667 }, scene: { background: '#f7f4ef', floor: { color: '#e8e0d4', type: 'whitewash-wood' }, lighting: { ambient: 0.6, natural: { x: 0.6, y: 0.25, intensity: 1.0, warmth: 5500 } }, placeholder: { x: 0.45, y: 0.43, width: 0.26, height: 0.32 } } }
    ],
    artistic: [
        { id: 'floating-abstract', name: 'Floating Abstract', description: 'Artwork in dreamlike space', category: 'artistic', baseResolution: { width: 3600, height: 2400 }, scene: { backgroundGradient: { from: '#1a1a2e', to: '#16213e', angle: 135 }, particles: true, lighting: { ambient: 0.3, key: { x: 0.5, y: 0.2, intensity: 1.0, warmth: 4000 } }, placeholder: { x: 0.5, y: 0.5, width: 0.35, height: 0.35, floating: true } } },
        { id: 'floral-surge', name: 'Floral Surround', description: 'Artwork with artistic florals', category: 'artistic', baseResolution: { width: 3800, height: 2533 }, scene: { background: '#faf7f2', florals: { style: 'artistic', position: 'corners', opacity: 0.6 }, lighting: { ambient: 0.5, natural: { x: 0.4, y: 0.2, intensity: 0.8, warmth: 4800 } }, placeholder: { x: 0.5, y: 0.48, width: 0.3, height: 0.4 } } },
        { id: 'gold-marble', name: 'Gold & Marble', description: 'Luxury gold and marble backdrop', category: 'artistic', baseResolution: { width: 3600, height: 2400 }, scene: { background: '#1a1a1a', surround: { material: 'gold-veil', opacity: 0.8 }, lighting: { ambient: 0.25, key: { x: 0.4, y: 0.3, intensity: 1.2, warmth: 3500 } }, placeholder: { x: 0.5, y: 0.5, width: 0.32, height: 0.42 } } },
        { id: 'smoke-mist', name: 'Smoke & Mist', description: 'Atmospheric smoke effect', category: 'artistic', baseResolution: { width: 3600, height: 2400 }, scene: { background: '#0d0d0d', atmosphere: { type: 'smoke', density: 0.4, color: '#2a2a3a' }, lighting: { ambient: 0.2, key: { x: 0.5, y: 0.3, intensity: 1.1, warmth: 3800 } }, placeholder: { x: 0.5, y: 0.5, width: 0.3, height: 0.4, glow: true } } }
    ],
    studio: [
        { id: 'clean-white', name: 'Clean White Studio', description: 'Pure white studio backdrop', category: 'studio', baseResolution: { width: 4000, height: 4000 }, scene: { background: '#ffffff', lighting: { ambient: 0.7, key: { x: 0.4, y: 0.3, intensity: 0.6, warmth: 5000 } }, placeholder: { x: 0.5, y: 0.5, width: 0.5, height: 0.5 } } },
        { id: 'infinity-curve', name: 'Infinity Curve', description: 'Seamless cyclorama', category: 'studio', baseResolution: { width: 3800, height: 2533 }, scene: { backgroundGradient: { from: '#f0f0f0', to: '#e0e0e0', curve: true }, lighting: { ambient: 0.6, key: { x: 0.5, y: 0.2, intensity: 0.7, warmth: 4800 } }, placeholder: { x: 0.5, y: 0.45, width: 0.4, height: 0.45 } } }
    ],
    exhibition: [
        { id: 'gallery-wall', name: 'Gallery Wall', description: 'Classic gallery wall with multiple pieces', category: 'exhibition', supportsMultiple: true, baseResolution: { width: 4800, height: 3200 }, scene: { background: '#f2f2f2', floor: { color: '#d9d9d9' }, wall: { color: '#e8e8e8' }, lighting: { ambient: 0.45, track: { intensity: 0.8, warmth: 3500 } } }, multiConfig: { maxArtworks: 6, arrangement: 'grid', spacing: 8 } },
        { id: 'exhibition-banner', name: 'Exhibition Banner', description: 'Professional exhibition with banner', category: 'exhibition', baseResolution: { width: 4000, height: 6000 }, scene: { background: '#1a1a1a', banner: { position: 'top', height: 0.15 }, lighting: { ambient: 0.3, key: { x: 0.5, y: 0.25, intensity: 1.0, warmth: 3800 } }, placeholder: { x: 0.5, y: 0.55, width: 0.4, height: 0.5 } } }
    ],
    packaging: [
        { id: 'wrapped-tissue', name: 'Wrapped in Tissue', description: 'Artwork in protective tissue', category: 'packaging', baseResolution: { width: 3200, height: 3200 }, scene: { background: '#f5f5f5', wrap: { material: 'tissue', opacity: 0.85, folds: true }, lighting: { ambient: 0.6, soft: true }, placeholder: { x: 0.5, y: 0.5, width: 0.6, height: 0.6, wrapped: true } } },
        { id: 'shipping-crate', name: 'Shipping Crate', description: 'Professional shipping crate', category: 'packaging', baseResolution: { width: 4000, height: 3000 }, scene: { background: '#2a2a2a', crate: { material: 'wood', hardware: 'metal' }, lighting: { ambient: 0.4, key: { x: 0.3, y: 0.4, intensity: 0.8, warmth: 4000 } } } }
    ]
};
TemplateLibrary.getAll = function() { return Object.values(this).flat(); };
TemplateLibrary.getByCategory = function(cat) { return this[cat] || []; };
TemplateLibrary.getById = function(id) { return this.getAll().find(t => t.id === id); };
TemplateLibrary.getCategories = function() { return [{ id: 'gallery', name: '🏛️ Gallery', count: this.gallery.length }, { id: 'residential', name: '🏠 Residential', count: this.residential.length }, { id: 'artistic', name: '🎨 Artistic', count: this.artistic.length }, { id: 'studio', name: '📸 Studio', count: this.studio.length }, { id: 'exhibition', name: '🖼️ Exhibition', count: this.exhibition.length }, { id: 'packaging', name: '📦 Packaging', count: this.packaging.length }]; };
TemplateLibrary.suggestTemplate = function(data) { return this.getAll().slice(0, 4); };